sudo: false
language: node_js
node_js:
  - '8'
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
install:
  - npm i npminstall && npminstall
before_script:
  - npm run migrate:up
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
services:
  - mysql