sudo: false
language: node_js
node_js:
  - 'latest'
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS realworld;'
install:
  - npm i npminstall && npminstall
before_script:
  - npm run migrate:up
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client