sudo: false
language: node_js
node_js:
  - '9'
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS realworld_test;'
install:
  - npm i npminstall && npminstall
before_script:
  - EGG_SERVER_ENV=unittest npm run migrate:up
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
services:
  - mysql